### ISSUE TITLE
SPARQL Validation

### ISSUE THREAD

**Issue by kasei** [mhausenblas/sparqlbin.com#2]
It would be great to have a validation button that could redirect to sparql.org's validation service.

**Comment by mhausenblas** [comment]
I've added a very simple integration in SHA: b08fcb4b4313b43d1431a4b86c96d0ade98dc7ea - lemme know if that works for you and I'll close this issue.

**Comment by kasei** [comment]
@mhausenblas yes, that works, thanks! Though it did take me a moment (and several clicks) to realize that the validation results were loading silently in the same window, but outside the viewable area. Perhaps there would be some way to make that more obvious?

**Comment by mhausenblas** [comment]
Point taken. Will fix this in M1 ...

**Comment by jindrichmynarz** [comment]
It would be enough if clicking on the "Validate" button would scroll the view to http://sparqlbin.com/#results.

**Comment by mhausenblas** [comment]
Good idea, thanks @jindrichmynarz!
