### ISSUE TITLE
Hash-based permalinks make portable use challenging

### ISSUE THREAD

**Issue by kasei** [mhausenblas/sparqlbin.com#3]
I don't know if the hash-based permalinks are inherent to the underlying architecture, but they restrict use of the service to user agents with javascript (I think). Having hash-less permalinks would not only allow any user agent to load the queries, but could then also be extended to allow conneg to provide the queries without markup (e.g. when requesting application/sparql-query or text/plain).

**Comment by mhausenblas** [comment]
@kasei - does the documentation I've provided now at https://github.com/mhausenblas/sparqlbin.com/wiki help answering this question?

**Comment by kasei** [comment]
@mhausenblas it helps, but it's not clear to me why the complexity is necessary. Why not have a single conneg URI that represents the query regardless of whether it is served as html, json, or raw sparql text? Is it even possible to directly access the raw sparql text, or must it be parsed out of json? I would think having the ability to directly reference the sparql query text by URI would help push forward the use and standardization of passing queries into endpoints by reference (e.g. using the query-uri parameter with some existing sparql protocol implementations).

(And please don't take this as criticism; I think this is a great service! Just trying to provide feedback and attempting to fully understand it.)

**Comment by mhausenblas** [comment]
@kasei I don't take this as criticism at all - quite the contrary. Very much appreciated! So one thing after the other:

>  Why not have a single conneg URI that represents the query regardless of whether it is served as html, json, or raw sparql text? 

That would be possible, yes, but that would also mean a page reload. I think of it more as two separate things: the SPARQLBin API that offers some functionality to manage the queries and SPARQLBin.com, the Web application, that happens to expose its state in a [certain way](http://www.w3.org/2001/tag/doc/IdentifyingApplicationState#AJAX).

> Is it even possible to directly access the raw sparql text, or must it be parsed out of json?

The query string is ATM part of the query entry (along with timestamp, etc.) and further things in the future (see #1) - but it's trivial to expose the raw query string via a sub-resource, say `http://sparqlbin.com/q/0f880d0a723f62393033a47ee955585c/querystr` - if that's what you want, can I ask you to file a separate issue for it (this one here, though very very useful for me is prolly not the right one to keep track of it ;)
